Update refined to 0.8.4 (#537)
* Update refined to 0.8.4

* Update Scala.js to 0.6.20

`requiresDOM := false` has been replaced with
`jsEnv := new org.scalajs.jsenv.nodejs.NodeJSEnv()` because of a
deprecation warning and sbt was updated 0.13.16 to prevent a
`java.lang.NoSuchMethodError: sbt.package$.Zero()Lsbt/Global$;` on
startup.