update ruby and jekyll. fix build error
https://travis-ci.org/julien-truffaut/Monocle/jobs/474094336#L478

```
2.77s$ gem update --system
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
Updating rubygems-update
The command "gem update --system" failed and exited with 1 during .
```